"""Constants and configuration for MTGNP."""

DEFAULT_PORT = 4444
MAX_PDU_SIZE = 65535
PING_INTERVAL = 30  # seconds
PONG_TIMEOUT = 10  # seconds
RECONNECT_TIMEOUT = 30  # seconds
MAX_DECK_SIZE = 50
MIN_DECK_SIZE = 1
INITIAL_LIFE = 20
HAND_SIZE = 7

# Phase order for validation
PHASE_ORDER = [
    "UNTAP", "UPKEEP", "DRAW", "PRECOMBAT_MAIN", "BEGIN_COMBAT",
    "DECLARE_ATTACKERS", "DECLARE_BLOCKERS", "ASSIGN_DAMAGE_ORDER",
    "FIRST_STRIKE_DAMAGE", "COMBAT_DAMAGE", "END_OF_COMBAT",
    "POSTCOMBAT_MAIN", "END_STEP", "CLEANUP"
]

PRIORITY_PHASES = ["UPKEEP", "DRAW", "PRECOMBAT_MAIN", "BEGIN_COMBAT",
                   "DECLARE_ATTACKERS", "DECLARE_BLOCKERS", "ASSIGN_DAMAGE_ORDER",
                   "FIRST_STRIKE_DAMAGE", "COMBAT_DAMAGE", "END_OF_COMBAT",
                   "POSTCOMBAT_MAIN", "END_STEP"]

GAME_STATES = ["LOBBY", "GAME_SETUP", "MULLIGAN", "IN_GAME", "GAME_OVER"]

ERROR_CODES = [
    "INVALID_JSON", "ILLEGAL_DECK", "UNKNOWN_TYPE", "STALE_ACTION",
    "NOT_YOUR_PRIORITY", "ILLEGAL_ACTION", "ILLEGAL_TARGET",
    "TRIGGER_ORDER_INVALID", "TRIGGER_CHOICE_INVALID", "INSUFFICIENT_MANA",
    "WRONG_PHASE", "DUPLICATE_ID"
]